//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merit.Web.Services.BankId {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merit.Web.Services.BankId.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starta BankID-appen..
        /// </summary>
        internal static string RFA1 {
            get {
                return ResourceManager.GetString("RFA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Försöker starta BankID-appen..
        /// </summary>
        internal static string RFA13 {
            get {
                return ResourceManager.GetString("RFA13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söker efter BankID, det kan ta en liten stund... Om det har gått några sekunder och inget BankID har hittats har du sannolikt inget BankID som går att använda för den aktuella identifieringen/underskriften i den här datorn. Om du har ett BankID-kort, sätt in det i kortläsaren. Om du inte har något BankID kan du hämta ett hos din internetbank. Om du har ett BankID på en annan enhet kan du starta din BankID-app där..
        /// </summary>
        internal static string RFA14_A_ {
            get {
                return ResourceManager.GetString("RFA14(A)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söker efter BankID, det kan ta en liten stund... Om det har gått några sekunder och inget BankID har hittats har du sannolikt inget BankID som går att använda för den aktuella identifieringen/underskriften i den här enheten. Om du inte har något BankID kan du hämta ett hos din internetbank. Om du har ettBankID på en annan enhet kan du starta din BankID-app där.
        /// </summary>
        internal static string RFA14_B_ {
            get {
                return ResourceManager.GetString("RFA14(B)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söker efter BankID, det kan ta en liten stund... Om det har gått några sekunder och inget BankID har hittats har du sannolikt inget BankID som går att använda för den aktuella identifieringen/underskriften i den här datorn. Om du har ett BankID-kort, sätt in det i kortläsaren. Om du inte har något BankID kan du hämta ett hos din internetbank..
        /// </summary>
        internal static string RFA15_A_ {
            get {
                return ResourceManager.GetString("RFA15(A)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söker efter BankID, det kan ta en liten stund... Om det har gått några sekunder och inget BankID har hittats har du sannolikt inget BankID som går att använda för den aktuella identifieringen/underskriften i den här enheten. Om du inte har något BankID kan du hämta ett hos din internetbank..
        /// </summary>
        internal static string RFA15_B_ {
            get {
                return ResourceManager.GetString("RFA15(B)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det BankID du försöker använda är för gammalt eller spärrat. Använd ett annat BankID eller hämta ett nytt hos din internetbank..
        /// </summary>
        internal static string RFA16 {
            get {
                return ResourceManager.GetString("RFA16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankID-appen verkar inte finnas i din dator eller telefon. Installera den och hämta ett BankID hos din internetbank. Installera appen från din appbutik eller https://install.bankid.com..
        /// </summary>
        internal static string RFA17_A_ {
            get {
                return ResourceManager.GetString("RFA17(A)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misslyckades att läsa av QR koden. Starta BankID-appen och läs av QR koden. Kontrollera att BankID-appen är uppdaterad. Om du inte har BankID-appen måste du installera den och hämta ett BankID hos din internetbank. Installera appen från din appbutik eller https://install.bankid.com..
        /// </summary>
        internal static string RFA17_B_ {
            get {
                return ResourceManager.GetString("RFA17(B)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starta BankID-appen..
        /// </summary>
        internal static string RFA18 {
            get {
                return ResourceManager.GetString("RFA18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du identifiera dig eller skriva under med BankID på den här datorn eller med ett Mobilt BankID?.
        /// </summary>
        internal static string RFA19 {
            get {
                return ResourceManager.GetString("RFA19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har inte BankID-appen installerad. Kontakta din internetbank..
        /// </summary>
        internal static string RFA2 {
            get {
                return ResourceManager.GetString("RFA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du identifiera dig eller skriva under med ett BankID på den här enheten eller med ett BankID på en annan enhet?.
        /// </summary>
        internal static string RFA20 {
            get {
                return ResourceManager.GetString("RFA20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiering eller underskrift pågår..
        /// </summary>
        internal static string RFA21 {
            get {
                return ResourceManager.GetString("RFA21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okänt fel. Försök igen..
        /// </summary>
        internal static string RFA22 {
            get {
                return ResourceManager.GetString("RFA22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åtgärden avbruten. Försök igen..
        /// </summary>
        internal static string RFA3 {
            get {
                return ResourceManager.GetString("RFA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En identifiering eller underskrift för det här personnumret är redan påbörjad. Försök igen..
        /// </summary>
        internal static string RFA4 {
            get {
                return ResourceManager.GetString("RFA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internt tekniskt fel. Försök igen..
        /// </summary>
        internal static string RFA5 {
            get {
                return ResourceManager.GetString("RFA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åtgärden avbruten..
        /// </summary>
        internal static string RFA6 {
            get {
                return ResourceManager.GetString("RFA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankID-appen svarar inte. Kontrollera att den är startad och att du har internetanslutning. Om du inte har något giltigt BankID kan du hämta ett hos din Bank. Försök sedan igen..
        /// </summary>
        internal static string RFA8 {
            get {
                return ResourceManager.GetString("RFA8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv in din säkerhetskod i BankID-appen och välj Legitimera eller Skriv under..
        /// </summary>
        internal static string RFA9 {
            get {
                return ResourceManager.GetString("RFA9", resourceCulture);
            }
        }
    }
}
